PRUEBAS/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MODELO;
using CrystalDecisions.Web;
using CrystalDecisions.Shared;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;

namespace PRUEBAS.Controllers
{
    public class AlumnoController : Controller
    {
        PruebasEntities pe = new PruebasEntities();
        // GET: Alumno
        public ActionResult ListaAlumnos()
        {
            return View(pe.sp_listaAlumnos().ToList());
        }



        //INICIO DE ACCION PARA EXPORTAR REPORTE SIN FILTRO
        public ActionResult ExportReport()
        {
            //List allEverest = new List();

            List<sp_listaAlumnos_Result> allEverest = new List<sp_listaAlumnos_Result>();

                allEverest = pe.sp_listaAlumnos().ToList();

            

            ReportDocument rd = new ReportDocument();
            
            rd.Load(Path.Combine(Server.MapPath("~/Reportes"), "ListaAlumno.rpt"));
            rd.SetDataSource(allEverest);

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            try
            {
                //=====================Inicio para Exportar a PDF============================================
                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);
                return File(stream, "application/pdf", "EverestList.pdf");
                //=====================Fin para Exportar a PDF===============================================

                //=====================Inicio para Exportar a Excel==========================================
                //Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.Excel);
                //stream.Seek(0, SeekOrigin.Begin);
                //return File(stream, "application/xls", "EverestList.xls");
                //=====================Fin para Exportar a Excel=============================================

                //=====================Inicio para Exportar a Word===========================================
                //Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.WordForWindows);
                //stream.Seek(0, SeekOrigin.Begin);
                //return File(stream, "application/doc", "EverestList.doc");
                //=====================Fin para Exportar a Word==============================================
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        //FIN DE ACCION PARA EXPORTAR REPORTE SIN FILTRO

        //INICIO DE ACCION PARA EXPORTAR REPORTE CON 1 FILTRO
        public ActionResult ReporteParametros(int? idPais)
        {
            List<sp_ReportePorPais_Result> allEverest = new List<sp_ReportePorPais_Result>();

            allEverest = pe.sp_ReportePorPais(idPais).ToList();

            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reportes"), "ListaAlumno.rpt"));
            rd.SetDataSource(allEverest);

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            try
            {
                //=====================Inicio para Exportar a PDF============================================
                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);
                return File(stream, "application/pdf", "EverestList.pdf");
                //=====================Fin para Exportar a PDF===============================================

                //=====================Inicio para Exportar a Excel==========================================
                //Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.Excel);
                //stream.Seek(0, SeekOrigin.Begin);
                //return File(stream, "application/xls", "EverestList.xls");
                //=====================Fin para Exportar a Excel=============================================

                //=====================Inicio para Exportar a Word===========================================
                //Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.WordForWindows);
                //stream.Seek(0, SeekOrigin.Begin);
                //return File(stream, "application/doc", "EverestList.doc");
                //=====================Fin para Exportar a Word==============================================
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        //FIN DE ACCION PARA EXPORTAR REPORTE CON 1 FILTRO

        //INICIO DE ACCION PARA EXPORTAR REPORTE CON 2 FILTROS
        public ActionResult ReporteParametros2(string Codigo, int? idPais)
        {
            List<sp_ReportePorPaisYcodigo_Result> allEverest = new List<sp_ReportePorPaisYcodigo_Result>();

            allEverest = pe.sp_ReportePorPaisYcodigo(Codigo, idPais).ToList();

            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reportes"), "ListaAlumno.rpt"));
            rd.SetDataSource(allEverest);

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            try
            {
                //=====================Inicio para Exportar a PDF============================================
                Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                stream.Seek(0, SeekOrigin.Begin);
                return File(stream, "application/pdf", "EverestList.pdf");
                //=====================Fin para Exportar a PDF===============================================

                //=====================Inicio para Exportar a Excel==========================================
                //Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.Excel);
                //stream.Seek(0, SeekOrigin.Begin);
                //return File(stream, "application/xls", "EverestList.xls");
                //=====================Fin para Exportar a Excel=============================================

                //=====================Inicio para Exportar a Word===========================================
                //Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.WordForWindows);
                //stream.Seek(0, SeekOrigin.Begin);
                //return File(stream, "application/doc", "EverestList.doc");
                //=====================Fin para Exportar a Word==============================================
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        //FIN DE ACCION PARA EXPORTAR REPORTE CON 2 FILTROS
    }



}

PRUEBAS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PRUEBAS.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PRUEBAS/Views/Alumno/ListaAlumnos.cshtml
@model IEnumerable<MODELO.sp_listaAlumnos_Result>

@{
    ViewBag.Title = "ListaAlumnos";
}

<h2>ListaAlumnos</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<!-- //INICIO PARA EXPORTAR REPORTE CON SIN FILTRO-->
<div class="form-group"><a href="@Url.Action("ExportReport")" class="btn btn-primary"> Generar Reporte</a></div>
<!-- //FIN PARA EXPORTAR REPORTE CON SIN FILTRO-->

<!-- //INICIO PARA EXPORTAR REPORTE CON 1 FILTRO-->
<div class="form-group">
    @using (Html.BeginForm("ReporteParametros", "Alumno"))
    {
        <div class="form-group">
            <input type="text" name="IdPais" id="IdPais" placeholder="ID PAIS" class="form-control"/>
            <input type="submit" name="enviar" value="GENERAR REPORTE" id="enviar" class="btn btn-default"/>
        </div>
    }
</div>
<!-- //FIN PARA EXPORTAR REPORTE CON 1 FILTRO-->

<!-- //INICIO PARA EXPORTAR REPORTE CON 2 FILTROS-->
<div class="form-group">
    @using (Html.BeginForm("ReporteParametros2", "Alumno"))
    {
        <div class="form-group">
            <input type="text" name="Codigo" id="Codigo" placeholder="CODIGO" class="form-control" />
            <input type="text" name="IdPais" id="IdPais" placeholder="ID PAIS" class="form-control" />
            <input type="submit" name="enviar" value="GENERAR REPORTE" id="enviar" class="btn btn-default" />
        </div>
    }
</div>
<!-- //FIN PARA EXPORTAR REPORTE CON 2 FILTROS-->

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellidos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdSexo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdProfesion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdPais)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellidos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Edad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdSexo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdProfesion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdPais)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

PRUEBAS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PRUEBAS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PRUEBAS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PRUEBAS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Alumno", "ListaAlumnos", "Alumno")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>